const pdfDocument = require('pdfkit')
const PlacoModel = require('./placoBill')

const placoDevis = async(req, res) => {
    const {
        title, price, surface,
        vice_placo_qte, vice_placo_prix, bande_armee_qte,
        bande_armee_prix, bande_joint_qte, bande_joint_prix, 
        enduit_colle_qte, enduit_colle_prix,
        enduit_lissage_qte, enduit_lissage_prix,
        corniere_qte, corniere_prix, plaque_placo_qte, plaque_placo_prix,
        cheville_qte, cheville_prix, fourrure_qte, fourrure_prix,
        } 
        = req.body
    const [day, number, month, year] = new Intl.DateTimeFormat('fr-CM', {'dateStyle':'full'}).format(new Date()).split(' ')
    const num = number.length === 1 ? '0'+ number : number
    const randomDoc = Math.floor(Math.random()* 10000)
    const doc = new pdfDocument()
    doc.font('Times-Roman')
    doc.pipe(fs.createWriteStream('public/devis/placo' + String(randomDoc) + '.pdf'))
    doc.image('public/devis/logo_renolux_cameroun.png',15  , 10, {scale:0.55})
    doc.fontSize(18).text(day, 350, 60)
    doc.fontSize(18).text(', ' +  String(num) +  month, 395, 60,{underline:true})
    doc.fontSize(18).text(year, 495, 60)
    doc.font('Times-Bold').fontSize(18).text('Entreprise: ', 28, 152)
    doc.fontSize(16).font('Times-Roman').text('RENOLUX CAMEROON', 125, 154)
    doc.font('Times-Bold').fontSize(18).text('Localisation: ', 28, 177)
    doc.fontSize(16).font('Times-Roman').text('Yaounde, CAMEROON', 137, 179)
    doc.font('Times-Bold').fontSize(18).text('Tel : ', 28, 202)
    doc.fontSize(16).font('Times-Roman').text('+237 691098037', 77, 204)
    doc.font('Times-Bold').fontSize(18).text('Mail : ', 28, 227)
    doc.fontSize(16).font('Times-Roman').text('renolux3@gmail.com', 83, 227)
    doc.font('Times-Bold').fontSize(18).text('Site web : ', 28, 249)
    doc.fontSize(16).font('Times-Roman').text('https://renolux.netlify.app', 113, 249)

    doc.lineCap('')
        .roundedRect(15, 135, 300, 140, 12)
        .stroke()
    doc.moveDown(2)
    doc.font('Times-Bold').fontSize(21) .text(title, {underline:true, align:'center'})   
    doc.moveDown(2)

    doc.lineCap('')
        .rect(23, 336, 580, 30).stroke()
        doc.font('Times-Bold').fontSize(16).fillColor('black') 
        .text('Designation', 30, 341)
        doc.lineCap('')
        .rect(182, 336, 100, 30).stroke()
        doc.font('Times-Bold').fontSize(16).fillColor('black') 
        .text('Quantite', 185, 341)
        doc.font('Times-Bold').fontSize(16).fillColor('black') 
        .text('Prix unitaire (FCFA)', 284, 341)
        doc.lineCap('')
        .rect(440, 336, 163, 30).stroke()
        doc.font('Times-Bold').fontSize(16).fillColor('black') 
        .text('Prix total ', 445, 341).stroke()

        doc.lineCap('')
        .rect(23, 366, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('vices placo', 30, 371)
        doc.lineCap('')
        .rect(182, 366, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(vice_placo_qte, 185, 371)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(vice_placo_prix, 284, 371)
        doc.lineCap('')
        .rect(440, 366, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( vice_placo_prix * vice_placo_qte, 440, 371)
        
        doc.lineCap('')
        .rect(23, 396, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Bandes armées', 30, 401)
        doc.lineCap('')
        .rect(182, 396, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(bande_armee_qte, 185, 401)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(bande_armee_prix, 284, 401)
        doc.lineCap('')
        .rect(440, 396, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( bande_armee_prix * bande_armee_qte, 440, 401)

        doc.lineCap('')
        .rect(23, 426, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Bandes a joints', 30, 431)
        doc.lineCap('')
        .rect(182, 426, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(bande_joint_qte, 185, 431)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(bande_joint_prix, 284, 431)
        doc.lineCap('')
        .rect(440, 426, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( bande_joint_prix* bande_joint_qte, 440, 431)

        doc.lineCap('')
        .rect(23, 456, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Enduit colles', 30, 461)
        doc.lineCap('')
        .rect(182, 456, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(enduit_colle_qte, 185, 461)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(enduit_colle_prix, 284, 461)
        doc.lineCap('')
        .rect(440, 456, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( enduit_colle_prix * enduit_colle_qte, 440, 461)

        doc.lineCap('')
        .rect(23, 486, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Enduit de lissage', 30, 491)
        doc.lineCap('')
        .rect(182, 486, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(enduit_lissage_qte, 185, 491)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(enduit_lissage_prix, 284, 491)
        doc.lineCap('')
        .rect(440, 486, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( enduit_lissage_prix * enduit_lissage_qte, 440, 491)

        doc.lineCap('')
        .rect(23, 516, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Cornières', 30, 521)
        doc.lineCap('')
        .rect(182, 516, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(corniere_qte, 185, 521)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(corniere_prix, 284, 521)
        doc.lineCap('')
        .rect(440, 516, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( corniere_prix * corniere_qte, 440, 521)

        doc.lineCap('')
        .rect(23, 546, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Plaque de placoplâtre', 30, 551)
        doc.lineCap('')
        .rect(182, 546, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(plaque_placo_qte, 185, 551)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(plaque_placo_prix, 284, 551)
        doc.lineCap('')
        .rect(440, 546, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( plaque_placo_prix * plaque_placo_qte, 440, 551)

        doc.lineCap('')
        .rect(23, 576, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Chevilles', 30, 581)
        doc.lineCap('')
        .rect(182, 576, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(cheville_qte, 185, 581)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(cheville_prix, 284, 581)
        doc.lineCap('')
        .rect(440, 576, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( cheville_prix * cheville_qte, 440, 581)

        doc.lineCap('')
        .rect(23, 606, 580, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text('Fourrures', 30, 611)
        doc.lineCap('')
        .rect(182, 606, 100, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(fourrure_qte, 185, 611)
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text(fourrure_prix, 284, 611)
        doc.lineCap('')
        .rect(440, 606, 163, 30).stroke()
        doc.font('Times-Roman').fontSize(16).fillColor('black') 
        .text( fourrure_prix * fourrure_qte, 440, 611)

        doc.lineCap('')
        .rect(23, 636, 580, 30).stroke()
        doc.font('Times-Bold').fontSize(16).fillColor('black') 
        .text('Montant total des désignations', 30, 641, {align:'center'})

        doc.lineCap('')
        .rect(440, 636, 163, 30).stroke()
        doc.font('Times-Bold').fontSize(16).fillColor('black') 
        .text( (fourrure_prix * fourrure_qte) + 
        (cheville_prix * cheville_qte) + 
        (plaque_placo_prix * plaque_placo_qte) + 
        (corniere_prix * corniere_qte) + 
        (enduit_lissage_prix * enduit_lissage_qte) + 
        (enduit_colle_prix * enduit_colle_qte) + 
        (bande_joint_prix* bande_joint_qte) + 
        (bande_armee_prix * bande_armee_qte) + 
        (vice_placo_prix * vice_placo_qte)
        , 440, 641)
        doc.font('Times-Roman').text(`Le mètre carré de la main-d’œuvre sera facturé à raison de ${price}F/m2 ceci fait un montant total de ${(price * surface).toFixed(2)} FCFA  pour une superficie de  ${surface}m2.`, 18, 680)
    doc.end()
    const newPlacoDevis = new PlacoModel(req.body)
    await newPlacoDevis.save()
    .then(()=>res.status(200).send('The placo devis is generated'))
    .catch((err)=> res.status(400).send(`An error occured, ${err}`))
}

module.exports = {placoDevis}